version: '3'

services:
  eoapi:
    # 从当前路径构建镜像
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: wangbaoqi1/vue3-admin-antd:latest
    env_file:
      - .env
